### ISSUE TITLE
Общие справочники\Объекты\Фильтр по объектам - нельзя кликнуть по заголовку для выбора всех объектов, надо целится по квадратику

### ISSUE THREAD

**Issue by telyakov** [tselishev-semen/Chocolate#168]
Общие справочники\Объекты\Фильтр по объектам - нельзя кликнуть по заголовку для выбора всех объектов, надо целится по квадратику

**Comment by tselishev-semen** [comment]
двойной клик, либо 'выделить все'  позволяют сделать это
